### ISSUE TITLE
Cron Support (Repeatable Jobs)

### ISSUE THREAD

**Issue by ferronrsmith** [elastic/esqueue#18]
cron + delayed job support. being able to schedule jobs to be executed at a future date/time.

e.g

```javascript
// An amount of miliseconds to wait until this job can be processed
// delayed can actually be ms since or epoch, either is fine.
var job = queue.addJob(type, payload, {delay:ms});


// Repeat job according to a cron specification.
// cron parser : https://github.com/harrisiirak/cron-parser
var job = queue.addJob(type, payload, {repeat:{cron:'*/2 * * * *', endDate: '2017-08-07 00:00:01'}});
```
See also: [delayed jobs](https://github.com/elastic/esqueue/issues/19)

**Comment by w33ble** [comment]
Can you fill in some details in the description? What sort of repeatable functionality are you looking for?

**Comment by ferronrsmith** [comment]
My use case for cron is.

I create snapshot of an elastic instance at the end of every week. Right not it's bash scripts... Having everything in elastic helps with auditing, then we can build a admin dashboard on top etc etc.

**Comment by tbragin** [comment]
@ferronrsmith Could you comment a bit on how you use 'esqueue'? What is the use case, overall?

**Comment by ferronrsmith** [comment]
@tbragin Just some background. Our data sanitation/preparation  infrastructure is built on entirely Elasticsearch. We use `esqueue` for all background task management (in conjunction with our task services). Just to name a few of this things...

1. Re-indexing collections to a another index
2. Applying data transformations. Most of the things [processors](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest-processors.html) does now and more .
3. All notifications through the platform.
4. Moving logs files from out NLU services into elastic

**Comment by w33ble** [comment]
Hey @ferronrsmith, we've decided to deprecate this repo and recommend that you do not use it in any of your projects. You're welcome to fork it and maintain your own fork, but Elastic won't be contributing to this repo any longer. As such, I'm going to close this issue request, and ultimately disable the issue tracker here. 

On a personal note, I think this use case is pretty neat.
